image: library/gradle:jdk10-slim

stages:
  - build
  - codequality
  - test
  - deploy

build-jar:
  stage: build
  script: ./gradlew shadowJar

validate-html:
  stage: build
  script: ./gradlew validateHTML

check-js:
  stage: codequality
  script: ./gradlew jshint

check-main-code:
  stage: codequality
  script: ./gradlew checkQualityMain

check-test-code:
  stage: codequality
  script: ./gradlew checkQualityTest

test:
  stage: test
  script: ./gradlew test

deploy:
  stage: deploy
  only:
    - master
  script:
    - echo "TODO - deploy internally"
  environment: production
